import { ArtAssetManifestEntry } from './art-asset';

/**
 * Static manifest of the first batch of imported art assets: furniture PNGs
 * from the "Furniture Map Assets" pack, all categorized under
 * "2minutetabletop" (the pack's author/publisher). Files live in
 * src/assets/map-maker/art/2minutetabletop/. This is a plain build-time
 * constant (no HTTP fetch) since the asset list never changes at runtime.
 */
export const ART_ASSET_MANIFEST: ArtAssetManifestEntry[] = [
  { fileName: 'Bed - Discarded mattress 5.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 1.a.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 1.b.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 1.c.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 1.d.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 1.e.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 1.f.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 5 - Cot.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 7.g.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 7.h.png', category: '2minutetabletop' },
  { fileName: 'Bed - Pattern 7.i.png', category: '2minutetabletop' },
  { fileName: 'Bedframe - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Armchair 1.a.png', category: '2minutetabletop' },
  { fileName: 'Chair - Armchair 1.b.png', category: '2minutetabletop' },
  { fileName: 'Chair - Armchair 1.c.png', category: '2minutetabletop' },
  { fileName: 'Chair - Armchair 1.d.png', category: '2minutetabletop' },
  { fileName: 'Chair - Bench 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Bench 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Cushion 1.a.png', category: '2minutetabletop' },
  { fileName: 'Chair - Cushion 1.b.png', category: '2minutetabletop' },
  { fileName: 'Chair - Cushion 1.c.png', category: '2minutetabletop' },
  { fileName: 'Chair - Latrine toilet 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Latrine toilet 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Simple - Broken 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Simple - Broken 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Simple 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Simple 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Simple 3 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Simple 4 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Simple 5 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Sofa 1 - Modular - Corner.png', category: '2minutetabletop' },
  { fileName: 'Chair - Sofa 1 - Modular - Straight.png', category: '2minutetabletop' },
  { fileName: 'Chair - Sofa 1.a.png', category: '2minutetabletop' },
  { fileName: 'Chair - Sofa 1.b.png', category: '2minutetabletop' },
  { fileName: 'Chair - Sofa 1.c.png', category: '2minutetabletop' },
  { fileName: 'Chair - Stool - Cushioned 1.png', category: '2minutetabletop' },
  { fileName: 'Chair - Stool 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Stool 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Chair - Throne - Stone.png', category: '2minutetabletop' },
  { fileName: 'Chest - Lockbox 1 - Iron.png', category: '2minutetabletop' },
  { fileName: 'Chest - Lockbox 2 - Wood.png', category: '2minutetabletop' },
  { fileName: 'Chest 1 - Steel.png', category: '2minutetabletop' },
  { fileName: 'Chest 2 - Gold.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Anvil 1.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Anvil 2.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Bird nest.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Book 1.a.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Book pile 1.a.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Book pile 2.a.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Book pile 3.a.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Book pile 4.a.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Book pile 5.a.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Broken boards 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Broken boards 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Bucket 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Bucket 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Clay jars 1.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Clay jars 2.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Covered.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Crystal ball.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Cutlery.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Firewood 1.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Firewood 2.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Flowers - No flowers.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Flowers 1.a.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Flowers 1.b.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Flowers 1.c.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Food 1.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Food 2.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Globe.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Grindstone - Dark.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Grindstone - Light.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Hammer and nails.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Inkwell.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Papers.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Pictures 1.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Pictures 2.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Pictures 3.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Pictures 4.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Playing cards.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Sacks 1.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Sacks 2.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Scales - Gold.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Scroll 1.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Scroll 2.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Scroll 3.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Scroll 4.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Scrolls.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Skull - Giant.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Skull - Human.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Tankards - Empty.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Tankards - Full.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Webs 9 - Full.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Webs 9 - Thin.png', category: '2minutetabletop' },
  { fileName: 'Clutter - Writing.png', category: '2minutetabletop' },
  { fileName: 'Cooking - Cauldron - Empty.png', category: '2minutetabletop' },
  { fileName: 'Cooking - Oven - Broken.png', category: '2minutetabletop' },
  { fileName: 'Cooking - Oven 1.png', category: '2minutetabletop' },
  { fileName: 'Cooking - Oven 2.png', category: '2minutetabletop' },
  { fileName: 'Cooking - Oven fireplace 3.png', category: '2minutetabletop' },
  { fileName: 'Cooking - Oven fireplace 4.png', category: '2minutetabletop' },
  { fileName: 'Cooking - Stove.png', category: '2minutetabletop' },
  { fileName: 'Curtain 1.png', category: '2minutetabletop' },
  { fileName: 'Feature - Altar - Gold.png', category: '2minutetabletop' },
  { fileName: 'Feature - Armillary sphere - Brass.png', category: '2minutetabletop' },
  { fileName: 'Feature - Bath tub - Large - Empty - Dark.png', category: '2minutetabletop' },
  { fileName: 'Feature - Bath tub - Large - Full - Dark.png', category: '2minutetabletop' },
  { fileName: 'Feature - Bath tub - Oval - Empty - Dark.png', category: '2minutetabletop' },
  { fileName: 'Feature - Bath tub - Oval - Full - Dark.png', category: '2minutetabletop' },
  { fileName: 'Feature - Bath tub - Small - Empty - Dark.png', category: '2minutetabletop' },
  { fileName: 'Feature - Bath tub - Small - Full - Dark.png', category: '2minutetabletop' },
  { fileName: 'Feature - Crustal ball.png', category: '2minutetabletop' },
  { fileName: 'Feature - Globe.png', category: '2minutetabletop' },
  { fileName: 'Feature - Loom 2.png', category: '2minutetabletop' },
  { fileName: 'Feature - Metal cage - Gold.png', category: '2minutetabletop' },
  { fileName: 'Feature - Orrery - Huge - Gold.png', category: '2minutetabletop' },
  { fileName: 'Feature - Orrery - Small - Gold.png', category: '2minutetabletop' },
  { fileName: 'Feature - Piano 1.a.png', category: '2minutetabletop' },
  { fileName: 'Feature - Piano 2.b.png', category: '2minutetabletop' },
  { fileName: 'Feature - Spinning wheel.png', category: '2minutetabletop' },
  { fileName: 'Feature - Statue 1 - Stone.png', category: '2minutetabletop' },
  { fileName: 'Feature - Statue 2 - Stone.png', category: '2minutetabletop' },
  { fileName: 'Feature - Statue 3 - Stone.png', category: '2minutetabletop' },
  { fileName: 'Feature - Suit of armor 1 - Silver.png', category: '2minutetabletop' },
  { fileName: 'Feature - Suit of armor 2 - Gold.png', category: '2minutetabletop' },
  { fileName: 'Feature - Telescope - Huge - Gold.png', category: '2minutetabletop' },
  { fileName: 'Feature - Telescope - Ladder - Dark.png', category: '2minutetabletop' },
  { fileName: 'Feature - Telescope - Ladder - Light.png', category: '2minutetabletop' },
  { fileName: 'Feature - Telescope - Medium - Gold.png', category: '2minutetabletop' },
  { fileName: 'Feature - Telescope - Small - Gold.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 1.a.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 1.b.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 1.c.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 2.a.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 2.b.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 2.c.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 3.a.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 3.b.png', category: '2minutetabletop' },
  { fileName: 'Light - Brazier 3.c.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle - Large - Lit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle - Large - Unlit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle - Small - Lit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle - Small - Unlit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle cluster - Lit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle cluster - Unlit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle stand - Lit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle stand - Small - Lit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle stand - Small - Unlit.png', category: '2minutetabletop' },
  { fileName: 'Light - Candle stand - Unlit.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier - Antler - Lit.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier - Antler - Unlit.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier 1 - Lit - Gold.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier 1 - Unlit - Gold.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier 2 - Lit - Iron.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier 2 - Unlit - Iron.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier 3 - Lit - Gold.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier 3 - Unlit - Gold.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier 4 - Lit - Iron.png', category: '2minutetabletop' },
  { fileName: 'Light - Chandelier 4 - Unlit - Iron.png', category: '2minutetabletop' },
  { fileName: 'Light - Lantern - Lit.png', category: '2minutetabletop' },
  { fileName: 'Light - Lantern - Unlit.png', category: '2minutetabletop' },
  { fileName: 'Light - Stand - Lit - Iron.png', category: '2minutetabletop' },
  { fileName: 'Light - Stand - Unlit - Iron.png', category: '2minutetabletop' },
  { fileName: 'Rug - Animal skin.png', category: '2minutetabletop' },
  { fileName: 'Rug - Bear 1.png', category: '2minutetabletop' },
  { fileName: 'Rug - Doormat 7.png', category: '2minutetabletop' },
  { fileName: 'Rug - Wrinkled 1.png', category: '2minutetabletop' },
  { fileName: 'Rug 6.a.png', category: '2minutetabletop' },
  { fileName: 'Rug 6.b.png', category: '2minutetabletop' },
  { fileName: 'Rug 6.c.png', category: '2minutetabletop' },
  { fileName: 'Rug 6.d.png', category: '2minutetabletop' },
  { fileName: 'Rug 6.e.png', category: '2minutetabletop' },
  { fileName: 'Rug 6.f.png', category: '2minutetabletop' },
  { fileName: 'Rug 6.g.png', category: '2minutetabletop' },
  { fileName: 'Statue platform.png', category: '2minutetabletop' },
  { fileName: 'Storage - Barrel - Broken - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Barrel 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Barrel 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Barrel 3 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Barrel 4.a - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Barrel 5.a - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Bookshelf 1.a - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Bookshelf 1.b - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Bookshelf 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Bookshelf 3 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Canvas bundle.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate - Broken 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate - Broken 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate 3 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate 4 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate 5 - Covered.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate 6 - Covered.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate 7 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crate 8 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crates 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Crates 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Dresser 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Dresser 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Modular shelf - Corner - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Modular shelf - Straight - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Shelf - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Shelf 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Shelf 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Storage - Vase 1.png', category: '2minutetabletop' },
  { fileName: 'Storage - Vase 2.png', category: '2minutetabletop' },
  { fileName: 'Storage - Wicker basket lid.png', category: '2minutetabletop' },
  { fileName: 'Storage - Wicker basket.png', category: '2minutetabletop' },
  { fileName: 'Table - Broken 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Broken 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - End 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - End 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - End 3 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - End 4 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - End 5 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - End 5.1.png', category: '2minutetabletop' },
  { fileName: 'Table - Long 1.png', category: '2minutetabletop' },
  { fileName: 'Table - Modular - Corner - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Modular - Straight - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Rectangle - Covered 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Rectangle - Covered 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Rectangle 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Rectangle 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Rectangle 3 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Rectangle 4 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Round 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Round 2 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Round 3 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Round 4 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Table - Writing desk - Dark.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Antlers.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Bear 1.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Deer.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Dragon - Large 1.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Dragon - Small 1.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Eyeball.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Fish 1.a.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Fish 2.b.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Lion.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Moose.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Tooth.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Wolf 1.png', category: '2minutetabletop' },
  { fileName: 'Trophy - Yeti.png', category: '2minutetabletop' },
  { fileName: 'Weapon - Axe  1.png', category: '2minutetabletop' },
  { fileName: 'Weapon - Axe  2.png', category: '2minutetabletop' },
  { fileName: 'Weapon - Shield 1.png', category: '2minutetabletop' },
  { fileName: 'Weapon - Shield 2.png', category: '2minutetabletop' },
  { fileName: 'Weapon - Sword 1.png', category: '2minutetabletop' },
  { fileName: 'Weapon - Sword 2.png', category: '2minutetabletop' },
  { fileName: 'Weapon - Sword 3.png', category: '2minutetabletop' },
  { fileName: 'Weapon rack 1 - Dark.png', category: '2minutetabletop' },
  { fileName: 'Weapon rack 2 - Dark.png', category: '2minutetabletop' },
];

